# theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs
title: Scrabble-bot
description: A simple bot that plays scrabble. It predicts the best move for a given board position.
search_enabled: false
aux_links:
  "Scrabble-Bot on GitHub":
    - "https://github.com/jinit24/Scrabble-bot"
aux_links_new_tab: true
